#!/bin/bash
#Todo: Add license info (GPL v2)
#Todo: Add copyright notice – dual copyright AyeAI and authorization
#Todo: Add change info with author name

#Install default version on caffe distributed on Ubuntu
sudo apt -y install caffe-cpu

#Build caffe from Ubuntu sources
sudo apt -y build-dep caffe-cpu
#Caffe CPUONLY uses ATLAS for BLAS
sudo apt -y install libatlas-base-dev

if [[ $(cat /etc/apt/sources.list | grep deb-src | grep -v ^# | wc -l) -lt 1 ]]
then
    echo Please enable software sources in software-properties-gtk
    #TODO: Add echo for appropriate help URL file 
    exit 0
else
    echo Found src URI
fi
apt-get -y source  caffe-cpu
#TODO: Add test whether the caffe source folder was created
#if [ -t caffe-1.0.0 ] then ...
#Search for how to check the existence of a folder
cd caffe-1.0.0/

#Use sed or awk to modify CmakeLists.txt to
# - turn on CPUONLY, turn off rest
cp CMakeLists.txt CMakeLists.txt.orig

#TODO: Explain what the awk command does, with links to a short note describing basic AWK skills
#TODO: The articles should be written as markdown (.md) files on Github
cat CMakeLists.txt.orig | awk '/CPU_ONLY/ {if ($7 == "OFF)") $7 = "ON)"};/./ {print $0}' > CMakeLists.txt


mkdir build
cd build
cmake ..
make all
#The following is a brute force for now and may 
sudo make install
make runtest
